---
- name: Plan and Stash
  hosts: localhost
  tasks:
    - name: Load the terraform plan file from variable into file
      cloud.terraform.plan_stash:
        path: terraform/terraform.tfplan
        state: load
        var_name: "demo_plan_var"
      #no_log: true

    - name: Terraform apply
      cloud.terraform.terraform:
        project_path: terraform/
        plan_file: ./terraform.tfplan
        force_init: true
        state: present
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
        variables:
          gcp_credentials: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
          gcp_project: "{{ lookup('env', 'GCE_PROJECT') }}"
