---
- name: Plan and Stash
  hosts: localhost
  tasks:
    - name: Terraform plan
      cloud.terraform.terraform:
        project_path: terraform/
        plan_file: ./terraform.tfplan
        force_init: yes
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
        variables:
          gcp_credentials_path: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
          gcp_project: "{{ lookup('env', 'GCE_PROJECT') }}"
      check_mode: true

    - name: Encode terraform plan file into a variable demo_plan_var
      cloud.terraform.plan_stash:
        path: terraform/terraform.tfplan
        state: stash
        var_name: "demo_plan_var"
      no_log: true
