---
version: 3

dependencies:
  galaxy: requirements.yml
  ansible_core:
    package_pip: ansible-core==2.16.4
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"

images:
  base_image:
    name: registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-25-ee-supported-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  append_base: |
    RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo | tee /etc/yum.repos.d/terraform.repo
    RUN microdnf install -y terraform

  append_final: |
    # Use Python 3.11 as default
    RUN rm -f /bin/python3
    RUN ln -s /bin/python3.11 /bin/python3

    # Output collections list for debugging
    RUN ansible-galaxy collection list

    # Display terraform version
    RUN terraform version
