---
- name: Ping EC2 Instances
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ping the EC2 instances
      ping:
      delegate_to: "{{ aws_instance_tf-demo-aws-ec2-instance-a.public_dns }}"
