---
- name: Run app
  hosts: all
  gather_facts: false
  strategy: free
  become: true

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
    - name: Ping Ec2 instance
      ansible.builtin.ping:
    - name: Install Podman
      ansible.builtin.yum:
        name:
          - podman
        update_cache: false
        state: present
